version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
      - "8020:8020"
    networks:
      - zeppelin-spark

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9864:9864"
    networks:
      - zeppelin-spark
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - "9865:9864"
    networks:
      - zeppelin-spark
   

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    ports:
      - "8032:8032"
      - "8088:8088"
    networks:
      - zeppelin-spark

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"
    networks:
      - zeppelin-spark

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"
    networks:
      - zeppelin-spark

  hive-metastore-mysql:
    image: mysql:8.0.21
    container_name: hive-metastore-mysql
    hostname: hive-metastore-mysql
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"
    networks:
      - zeppelin-spark

  hive-server:
    image: kadensungbincho/hadoop-hive-mysql:hive3.1.2-hadoop3.2.1-java8
    container_name: hive-server
    hostname: hive-server
    depends_on:
      - resourcemanager
      - nodemanager
      - historyserver
      - hive-metastore
    volumes:
      - ./dummy_data:/opt/dummy_data
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"
      DUMMY_DATA: 1
    ports:
      - "10000:10000"
    networks:
      - zeppelin-spark

  hive-metastore:
    image: kadensungbincho/hadoop-hive-mysql:hive3.1.2-hadoop3.2.1-java8
    container_name: hive-metastore
    hostname: hive-metastore
    depends_on:
      - hive-metastore-mysql
    env_file:
      - hadoop.env
    command: [ "startup.sh", "metastore" ]
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-mysql:3306"
    ports:
      - "9083:9083"
    networks:
      - zeppelin-spark

  zookeeper:
    image: zookeeper:3.4.14
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - zeppelin-spark
volumes:
  namenode:
  datanode:
  hadoop_historyserver:

networks:
  zeppelin-spark:
    external: true

